import { ModalType } from '../types/ModalTypes';

export const DELETE_DASHBOARD: ModalType = 'DELETE_DASHBOARD';
export const CHART_SELECTOR: ModalType = 'CHART_SELECTOR';
export const DELIVERABLES: ModalType = 'DELIVERABLES';
export const ADVANCE_FILTERS: ModalType = 'ADVANCE_FILTERS';
export const UPDATE_VALUES_ACTION: ModalType = 'UPDATE_VALUES_ACTION';
export const COMPARISON_BY_PARAMETERS_MODAL_CONTENT = 'COMPARISON_BY_PARAMETERS_MODAL_CONTENT';
export const REPORTABLE_COMPROMISES_MODAL_CONTENT = 'REPORTABLE_COMPROMISES_MODAL_CONTENT';
export const SUMMARY_COMPROMISE_MODAL_CONTENT = 'SUMMARY_COMPROMISE_MODAL_CONTENT';
export const PERFORMANCE_EVALUATION_MODAL_CONTENT = 'PERFORMANCE_EVALUATION_MODAL_CONTENT';
